# This is a basic workflow to help you get started with Actions

name: Catalogue

# Controls when the action will run. 
on:
  #schedule:
    # - cron:  '0 3,9,15,21 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
   
    - name: Checkout script repo
      uses: actions/checkout@v2
            
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    
    - name: Catalogue
      run: python ./data/catalogue.py
    
    - name: Commit files
      run: |
        git config user.name Catalogue
        git add .
        git commit -m "Commit `date +'%Y-%m-%d %H:%M:%S'`" || echo "Nothing to commit"
        git push -f origin main
