# This is a basic workflow to help you get started with Actions

name: Hourly Scrape

# Controls when the action will run. 
on:
  schedule:
    - cron:  '0 */1 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
   
    - name: Checkout script repo
      uses: actions/checkout@v2
            
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests croniter
    
    - name: Run scraper
      run: python ./data/getData.py
      
    - name: Commit files
      run: |
        git config user.name 4very
        git config user.email asommer999@gmail.com
        git add .
        git commit -m "Commit `date +'%Y-%m-%d %H:%M:%S'`" || echo "Nothing to commit"
        git push -f origin main
