# This is a basic workflow to help you get started with Actions

name: Test File

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  

jobs:
  Scrape:
    runs-on: ubuntu-latest
    steps:
   
    - name: Checkout script repo
      uses: actions/checkout@v2
            
    - name: create file
      run: touch test.txt
      
    - name: Commit files
      run: |
        git config user.name Scraper
        git add .
        git commit -m "Commit `date +'%Y-%m-%d %H:%M:%S'`" || echo "Nothing to commit"
        git pull origin main -s recursive -X ours --rebase
        git push origin main
