# This is a basic workflow to help you get started with Actions

name: Vercel Deploy

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  

jobs:
  Scrape:
    runs-on: ubuntu-latest
    steps:
   
    - name: Checkout script repo
      uses: actions/checkout@v2
            
    - name: Trigger Vercel Redeploy
      uses: amondnet/vercel-action@v20
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
        vercel-args: '--prod' #Optional
        vercel-org-id: ${{ secrets.ORG_ID}}  #Required
        vercel-project-id: ${{ secrets.PROJECT_ID}} #Required 
